version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    registries:
      - jfrog-artifactory

registries:
  jfrog-artifactory:
    type: "maven-repository"
    url: "https://jfrogghdemo.jfrog.io/artifactory/dependabot/"
    username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
    password: "${{ secrets.JFROG_ARTIFACTORY_TOKEN }}"
